server:
  port: 8082
spring:
  artemis:
    password: 'simetraehcapa'
    user: 'artemis'
  mail:
    host: 'smtp.yandex.ru'
    username: 'pztest'
    password: 'bijzomabgjgbhccv'
    protocol: 'smtp'
    properties:
        mail:
          smtp:
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
            port: 465
            auth: 'true'
            ssl:
              enable: 'true'
            starttls:
              enable: 'true'
              required: 'true'
  profiles:
    active: ${SPRING_PROFILES_INCLUDE:dev}
spring.datasource:
  url: "jdbc:postgresql://localhost:5432/gb_shop"
  username: "geek"
  password: "geek"

